### ISSUE TITLE
Add more explanations/links to Builder 

### ISSUE THREAD

**Issue by ehsanmok** [dtolnay/proc-macro-workshop#12]
Hi 

Following up on the builder tutorial, I found the transition to `06-optional-field` to the end is tough. It'd help a lot to explain a little in more details what to do or link to similar code about how to check whether `Option` exists or not in `06`.

**Comment by dtolnay** [comment]
Thanks! I have added some more detail to 06-optional-field. Please let me know if it is still unclear how I expect for that part of the macro to work.
