### ISSUE TITLE
Help with `Seq` macro

### ISSUE THREAD

**Issue by ELD** [dtolnay/proc-macro-workshop#20]
Hi! I'm working on implementing the Seq macro and I'm getting a little stuck. It alludes to treating the body of the expression as a `TokenStream` and not as some type of `syn` AST structure.

I can parse out everything that's instructed in the `01-parse-header.rs` file, but when I get to `02-parse-body.rs`, I get stuck on how to treat the loop body of the macro as a `TokenStream`. Additionally, when I attempt to run `cargo test`, I get an error on unexpected tokens.

The error message:
```
Testing tests/01-parse-header.rs ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error: unexpected token
  --> $DIR/01-parse-header.rs:25:16
   |
25 |   seq!(N in 0..8 {
   |  ________________^
26 | |     // nothing
27 | | });
   | |_^
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

Link to the code I have so far: https://github.com/ELD/proc-macro-workshop/blob/seq-macro/seq/src/lib.rs

Any guidance would be appreciated!

**Comment by dtolnay** [comment]
A good example would be Attribute which also parses part of its representation as TokenStream.
https://docs.rs/syn/0.15/syn/struct.Attribute.html

Unexpected tokens are anything that you didn't parse.

**Comment by ELD** [comment]
Huh, I don't know why I didn't put two-and-two together. That's been useful to look at as an example!

I have the first two test cases working as expected with the body in a `TokenStream` representation. Thanks!
