### ISSUE TITLE
Learning documents

### ISSUE THREAD

**Issue by gnzlbg** [dtolnay/proc-macro-workshop#22]
Is there a presentation or book or blog posts that can be followed to learn the necessary knowledge required to accomplish the workshop ?

**Comment by Robbepop** [comment]
As far as I know there was an initial workshop at Rust Latam but I wasn't able to find any recordings of it. The spirit of the workshop is learning by doing. It is definitely feasible and works quite well. Also there are guidlines which problem to pick based on your own Rust experience.

**Comment by rajivr** [comment]
I would highly recommend checking out Jon Gjengset videos.

https://www.youtube.com/watch?v=geovSK3wMB8

https://www.youtube.com/watch?v=KVWHT1TAirU

**Comment by Tomaz-Vieira** [comment]
Also, the `syn` library has beautifully commented [examples](https://github.com/dtolnay/syn/tree/master/examples/)

**Comment by timmyjose** [comment]
@gnzlbg That's what I'd expected as well - the workshop materials plus some sample solutions at least for guidance. Sadly, neither proper learning materials nor sample solutions are provided.

**Comment by jmg-duarte** [comment]
I've recently started doing the workshop and the following resources were helpful (some were already presented):
- `derive(Builder)` - Jon Gjengset videos [[1](https://www.youtube.com/watch?v=geovSK3wMB8), [2](https://www.youtube.com/watch?v=KVWHT1TAirU)].
- `derive(CustomDebug)` - The [`syn`](https://docs.rs/syn/1.0.54/syn/index.html), [`quote`](https://docs.rs/quote/1.0.7/quote/), [`proc_macro2`](https://docs.rs/proc-macro2/1.0.24/proc_macro2/). I also recommend reading every progress test before even starting, some may not resonate at first but when going through the tests it will make conscious of challenges to keep in mind.
- `seq!` - David's [`seq-macro`](https://github.com/dtolnay/seq-macro), you can sidestep `parse.rs` by using `syn` but I still recommend reading all the source code
- `#[sorted]` - Read Jon Gjengset [implementation](https://github.com/jonhoo/proc-macro-workshop/tree/master/seq)

I've also implemented most of the macros (excluding `bitfield`), you can take a look here https://github.com/rustype/proc-macro-workshop
I tried to keep them readable and document the more complicated code.
As it stands, `CustomDebug` requires some refactoring though.

**Comment by martin-t** [comment]
I found [this really nice repo](https://github.com/WhoisDavid/rust-learnings#procedural-macros-workshop) with implementations of all 5 proc macros (and other things). I only skimmed it but the code seems pretty clean and well commented.

**Comment by minhuw** [comment]
For anyone interested in this workshop but has not read the code: You may read the document at the top of each test case, for example, `builder/tests/01-parse.rs`, to get some guidance. It tells what the test case expects and gives helpful reading resources, such as documents of used crate and struct and code examples. Following test cases in order may be enough to complete this workshop.

**Comment by dtolnay** [comment]
I think these days google has enough procedural macro content. Many of the test cases have links to documentation that I consider especially relevant, but in general everyone will use whatever style of resources works for them.
