### ISSUE TITLE
Feature request: examples using proc-macro2 and darling

### ISSUE THREAD

**Issue by ckaran** [dtolnay/proc-macro-workshop#31]
Thank you for creating this project!  It's what I've been looking for to learn how to write procedural macros in rust.

I noticed that you are the co-author of the [proc-macro2](https://github.com/dtolnay/proc-macro-workshop.git) crate; could you add some examples of how to use that crate here?  Also, could you give examples of how to use [darling](https://crates.io/crates/darling)?

I know nothing about writing macros, but want to learn how to do so correctly so that end users actually want to use my macros, instead of feeling that they have to use them.  So once again, thank you for making this project!

**Comment by dmgolembiowski** [comment]
@ckaran There are some nice demos of [darling](https://github.com/TedDriggs/darling/blob/master/examples/consume_fields.rs#L132) example usage. Also about 2 weeks ago, the [proc-macro-2](https://github.com/alexcrichton/proc-macro2/blob/master/tests/marker.rs) repository updated its test suite. Looking at tests are a great way to potentially discover an alternative to explicitly labeled "examples". They also show you interesting tools for making tests for your own stuff.

**Comment by ckaran** [comment]
@dmgolembiowski Thank you for the suggestions, I'll look into them as well.

**Comment by dtolnay** [comment]
I am not a fan of the darling crate so I don't feel the need to cover it.

For proc-macro2 &mdash; I think this is already sufficiently covered by the workshop, especially the `seq!` project which involves directly working with tokens and not syntax trees.

**Comment by ckaran** [comment]
> I am not a fan of the darling crate so I don't feel the need to cover it.

Can you please elaborate on why?  I know so little about writing proc macros that any explanations of what I should be looking out for are always appreciated.
