### ISSUE TITLE
Why span in `compile_error!` error message include the ending `;` ?

### ISSUE THREAD

**Issue by minhuw** [dtolnay/proc-macro-workshop#43]
I use `rustc 1.54.0 (a178d0322 2021-07-26)`, in `seq/tests/03-expand-four-errors.rs`, span in the expected error message doesn't include the ending `;` as shown below.
```
error: error number 0
  --> tests/03-expand-four-errors.rs:20:5
   |
20 |     compile_error!(concat!("error number ", stringify!(N)));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However, my solution gives an almost equal version except that the span `^` includes the ending ';'.

```
error: error number 0
  --> tests/03-expand-four-errors.rs:20:5
   |
20 |     compile_error!(concat!("error number ", stringify!(N)));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I try to add `compile_error!` explicitly, and the error message also includes the ending `;`.
```
error: error number 0
  --> main.rs:13:5
   |
13 |     compile_error!(concat!("error number ", stringify!(0)));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I wonder whether it's just an compiler version issue or it's intended to be so and I should figure out how to control the span in error meesage generated by `compile_error!`?

**Comment by dtolnay** [comment]
According to bf98356081b52ad3d74f04584c0d9d205ad52c18 any compiler newer than 2021-10-17 would not be including the semicolon in the span.

**Comment by minhuw** [comment]
Thank you for your help, I update my rustc to `2021-11-29` and it gives expected error message.
