### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by sharedrory** [dtolnay/proc-macro-workshop#47]
Sorry if its really obvious. Where do I find the article, video, or whatever I am supposed to follow along?

**Comment by anvlkv** [comment]
@sharedrory start here https://github.com/dtolnay/proc-macro-workshop/blob/8e8be4c9508eeb47c7825659bcced527da46054f/builder/tests/01-parse.rs#L8

**Comment by sharedrory** [comment]
I see. So we have to work through to make all the tests pass?

**Comment by fortressia** [comment]
> I see. So we have to work through to make all the tests pass?

Yeah, once you completed all the tests, continue on the next test, or alternatively on the one chapter that you really need to understand ASAP.
