### ISSUE TITLE
Unused code warning in sorted 04

### ISSUE THREAD

**Issue by robamu** [dtolnay/proc-macro-workshop#54]
I received unused import warnings which lead to a compile error missmatch for an otherwise correct test 04.
I solved this issue by adding `#![allow(unused_imports)]` to the 04 code and adapting the line numbers in the *.stderr file.

**Comment by dtolnay** [comment]
Which import is unused?

**Comment by robamu** [comment]
Okay, I actually did a mistake and emitted a compile error instead of the input stream. The correct approach was to append the compile error to the input stream.
