### ISSUE TITLE
Seq05 would break multiple other tests.

### ISSUE THREAD

**Issue by fatboyzz** [dtolnay/proc-macro-workshop#60]
Seq05 introduced new rule to only repeat tokens inside `#( ... )*`.
This new rule would cause other tests fall since they don't have their full body inside `#( ... )*`.
Broken tests are Seq02, Seq03, Seq04, Seq08 .

**Comment by dtolnay** [comment]
You should implement this in a way that all those tests continue to pass.

**Comment by fatboyzz** [comment]
Thanks for your quick reply.
Seems I have to do a pre scan of full seq body just to determine whether there is `#(...)*` inside it.
Otherwise I can't tell if I should repeat the seq body at the beginning.
I tend to think seq's syntax which allow implicit full body repeat is not a good design.

**Comment by dtolnay** [comment]
Okay!
