### ISSUE TITLE
The build function in Builder derive macro should take ownership

### ISSUE THREAD

**Issue by dupeiran001** [dtolnay/proc-macro-workshop#70]
In the build derive macro, `04-call-builder`, the `build` function takes a `&mut self`, and it returns a `Command` with the ownership of the fields. So I have to `clone` the fields in the implementation, which is not correct I suppose. 

The build function should take the ownership of Builder, and return a builded result.

like this:

```rust
fn build(self) -> Result<Command, dyn Error>{
    unimplemented!()
}
```

**Comment by shouya** [comment]
> So I have to clone the fields in the implementation

To avoid cloning, you can look into `Option::take` as well as `Vec::split_off`.

**Comment by dtolnay** [comment]
This exercise is inspired by the real API of `std::process::Command`, which takes `&mut self` in its equivalent of a `build` method.
https://doc.rust-lang.org/1.81.0/std/process/struct.Command.html#method.spawn
